# Generated by Django 4.2.20 on 2025-09-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
    ]
